name: R CMD Check para datamedios

# Aquí definimos cuáles son los eventos que activan el flujo de trabajo
# Este por ejemplo se activa cada vez que hacemos pull o push a la rama 'main'
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Esto al parecer por lo general no se cambia, da solo permisos de lectura
permissions:
  contents: read


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        r-version: ['4.1.1', '4.4.1', 'devel']

    steps:
      - uses: actions/checkout@v4
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(error_on = "error")
        shell: Rscript {0}
      - name: Verify Rscript
        run: Rscript --version
        shell: bash
